### ISSUE TITLE
Read file permissions in standalone mode

### ISSUE THREAD

**Issue by jcugmas** [tiagorangel1/cap#23]
Hi everyone,

I'm opening this issue because I'm facing to access file permissions error logs using Cap in standalone mode with Docker.
I'm building my image using docker compose 

```
cap:
    image: tiago2/cap:latest
    networks:
      - myNetwork
    ports:
      - "3000:3000"
    environment:
      - ADMIN_KEY=abcdefghijkl123456789
    volumes:
      - cap:/usr/src/app/.data
```

After the image was build and launched, I get the following error log 

```
[asset server] error updating assets cache, trying to load them might fail: EACCES: permission denied, open '.data/assets-cache.json'
    path: ".data/assets-cache.json",
 syscall: "open",
   errno: -13,
    code: "EACCES"
```

Sometimes it can happen on the file keys.json and if so, the image cannot start.

Is it because I'm using for now a simple named volume ?

Moreover, I don't know if it's related but I have some errors when checking private key on uri /siteverify.
Do we agree that the env variable ADMIN_KEY is used as private key ?
Because if that so, I'm always getting an error 400 with message "Invalid Secret Key", I have debugged the code by just adding some log and I get 

```
Received secret: [abcdefghijkl123456789]
Received hashed secret: [$argon2id$v=19$m=65536,t=2,p=1$g+olRaovQ/eNnF7itYe+5mh7hPJJu+wvw5hkCTBIpMg$sIDPGwozlyzMGmQYQdA3YNuwdJN1+AyTo+8yiKTsIio]
Stored   hashed secret: [$argon2id$v=19$m=65536,t=2,p=1$tGBXS3qYjRY03zeECGuZv0odVmErCiGoVgPp9Ftn/v8$9zrq3nWbl9QoQU4lEFWrz5aO8DXg0mUh6rj0TmOOOdw]
```

Am I doing something wrong ?

Thank you

Best regards

**Infomration:**
 - OS: Fedora 40
 - Docker version: 28.1.1
 - Docker desktop version: 4.41.1
